### ISSUE TITLE
breakfast a5xelte/a5xeltexx

### ISSUE THREAD

**Issue by itsmerajit** [Exynos7580/android_hardware_samsung_slsi-cm_exynos7580#3]
i am getting this error

breakfast a5xeltexx
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_a5xeltexx".  Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "cm_a5xeltexx".  Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_a5xeltexx".  Stop.
Device a5xeltexx not found. Attempting to retrieve device repository from lineageos Github (http://github.com/LineageOS).
Repository for a5xeltexx not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_a5xeltexx".  Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_a5xeltexx".  Stop.

** Don't have a product spec for: 'lineage_a5xeltexx'
** Do you have the right repo manifest?

**Comment by Stricted** [comment]
you cant just breakfast it, since this is not an official supported device by lineageos you have to create the manifest yourself

edit: also you are on the wrong repo, if you have issues with the a5xeltexx go to https://github.com/Exynos7580/android_device_samsung_a5xeltexx
im going to close this issue here

**Comment by itsmerajit** [comment]
Able to create manifest.. now stuck at jack error in 8gb pc. Cant able to restart it. Its fail to restart it says

**Comment by bunnyyTheFreak** [comment]
how to create manifest for the same??
