### ISSUE TITLE
Stuck at splash screen

### ISSUE THREAD

**Issue by dkati** [Exynos7580/android_hardware_samsung_slsi-cm_exynos7580#4]
good evening people.
i built those ->
https://github.com/Stricted/LineageOS_build/blob/master/manifests/s5neoltexx.xml

and i get stuck at splash screen.

clean build / full wiped my device.
do we have to track los-14.1 branch or cm-14.1 of s5neo tree ?

**Comment by ghost** [comment]
You have to track the `los-14.1` branch, it contains last commits
For instance, i don't maintain the s5neo, i don't tested it so i can't answer you problem

Regards

**Comment by dkati** [comment]
@vlourme thanks for that fast reply.

the branches that are marked at the manifest,are the latest

**Comment by Stricted** [comment]
resolved
